### ISSUE TITLE
Associate .ui files with QtCreator

### ISSUE THREAD

**Issue by pquiring** [andisfar/LaunchQtCreator#1]
It would be nice if .ui files were associated with QtCreator so user could right click and open them in QtCreator.

Thanks,

**Comment by andisfar** [comment]
@pquiring thank you for your input.  I will definitely add this one to my list of features.  I am also planning a feature that will open project files (.pro or CMakeLists.txt files) in QtCreator as well.
Stay tuned

**Comment by andisfar** [comment]
@pquiring the extension with version 0.0.3 now opens ui files in qtcreator or in designer (dealers choice) and there are now commands to open project files (*.pro and CMakeLists.txt) in qtcreator.  Resource files (*.qrc) can also be opened in qt creator
