### ISSUE TITLE
spaces in path file path makes designer fail to load

### ISSUE THREAD

**Issue by amarco** [andisfar/LaunchQtCreator#14]
I have a workspace whose absolute path contains spaces.
When I attempt to open a .ui file using "Open in Qt Designer" context menu option designer complains that it cannot open the file. Looking at the messages it is clear the spaces are buggering things up. How do I specify quotes around the full path url and name so designer does not treat a string with spaces as multiple arguments.

Thanks
Marco

**Comment by andisfar** [comment]
I will look into this, and thanks for bringing it to my attention.

**Comment by andisfar** [comment]
I have added code to wrap filenames in double quotes, which has worked on my one test machine.
This should address issues with spaces in file names.
