### ISSUE TITLE
What do you find Qt Creator invaluable or more convenient for, compared to VS Code?

### ISSUE THREAD

**Issue by kaheimri** [andisfar/LaunchQtCreator#23]
Hi, I'm working on the Qt VS Tools extension and I'm really curious to find out which tasks you prefer to use Qt Creator for, instead of VS Code. I would be glad if you could share your experience with me.

Best regards,
Karsten

**Comment by andisfar** [comment]
I think it comes down to intelligence, VS Code with extensions is pretty descent with intelligence for c++ in general, but not specifically with Qt, I also prefer using Qt Creator or designer for creating Audi files/classes.  Ui can be done with out, but simpler wit.  I also work in a restrictive offline environment with a low budget.  
with Qt and CMake i don’t like Qts method of arranging were the build directory is setup.  I realize that the build location can be modified with in Qt Creator simply enough, but VS Code is even more simply.  I got tired of going through the application menu to start Qt (mostly always started in VS Code), so,  being a lazy developer , I made a way to switch to Qt from inside of VS Code.
